# 头部菜单，title: link
menu:
  Whoami: /whoami
  Archives: /archives
  Motto: https://motto.rudymemo.com/
  Music: https://music.rudymemo.com/
  MyTrails: https://trails.rudymemo.com/

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: true

# 默认音乐
mp3: 
  - /music/退了色的香味 - V.A.mp3
  - /music/退了色的香味 - V.A.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: 'https://cdn.jsdelivr.net/gh/rudymemo/picx.xpoet.cn/202204261118212.jpg'

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: '97907f825d3f3e1f86a9'
    # 应用秘钥
    clientSecret: '7036505292a06ee529c894375bca66cc6350d69a'
    # issue仓库名
    repo: 'rudymemo.github.io'
    # Github名
    owner: 'rudymemo'
    # Github名
    admin: ['rudymemo']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: rudymemo

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
